project: 
  type: website
  output-dir: "." 

website:
  title: "Jacob Miller"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Project
        href: projects.html
      - text: Blog
        href: blog-listing.qmd
      - text: "Python Data Analytics"
        menu:
          - pandas_basics.ipynb
          - seaborn_basics.ipymb
            
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© Jacob Miller, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: true
    include-after-body: target_blank.html

