<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jacob Miller">
<meta name="dcterms.date" content="2025-05-16">

<title>ESG Project – Jacob Miller</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Jacob Miller</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./danl_210_Miller_Jacob_stock_ESG (5).html" aria-current="page"> 
<span class="menu-text">ESG Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./blog-listing.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-python-data-analytics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Python Data Analytics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-python-data-analytics">    
        <li>
    <a class="dropdown-item" href="./pandas_basics (1).html">
 <span class="dropdown-text">Pandas Basics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./seaborn_basics.html">
 <span class="dropdown-text">Seaborn Basics</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection">Data Collection</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#statistics-continued" id="toc-statistics-continued" class="nav-link" data-scroll-target="#statistics-continued">Statistics Continued</a></li>
  <li><a href="#data-visualization" id="toc-data-visualization" class="nav-link" data-scroll-target="#data-visualization">Data Visualization</a></li>
  <li><a href="#combining-return-and-esg-risk" id="toc-combining-return-and-esg-risk" class="nav-link" data-scroll-target="#combining-return-and-esg-risk">Combining Return and ESG Risk</a></li>
  <li><a href="#correlation-and-heat-map" id="toc-correlation-and-heat-map" class="nav-link" data-scroll-target="#correlation-and-heat-map">Correlation and Heat Map</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ESG Project</h1>
  <div class="quarto-categories">
    <div class="quarto-category">python</div>
    <div class="quarto-category">data organization</div>
    <div class="quarto-category">data manipulation</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jacob Miller </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="background" class="level1">
<h1>Background</h1>
<p>In recent years, the importance of Environmental, Social, and Governance (ESG) performance has grown significantly among investors and regulatory bodies. ESG metrics are now seen as essential indicators of a company’s long-term stability, ethical conduct, and risk exposure. Despite this shift, traditional financial indicators such as revenue growth, profit margins, and stock performance continue to drive investment decisions. Gaining insight into how ESG risk scores change over time and how they correlate with financial outcomes can help companies align sustainable practices with long-term value creation.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This project explores the relationship between a companys ESG risk score and its financial performance. By integrating ESG data with key financial indicators, the goal is to uncover trends that may support more responsible, sustainability-oriented investment decisions.</p>
</section>
<section id="data-collection" class="level1">
<h1>Data Collection</h1>
<p>Python selenium web-scraping of Yahoo Finance data</p>
<div id="cell-4" class="cell" data-outputid="202f555b-178c-4426-964b-e6cba3e7d8f9" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pandas.plotting <span class="im">import</span> scatter_matrix</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load saved CSVs</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>url_2024 <span class="op">=</span> <span class="st">"https://bcdanl.github.io/data/esg_proj_2024_data.csv"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>esg_proj_2024_data <span class="op">=</span> pd.read_csv(url_2024)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"https://bcdanl.github.io/data/stock_history_2023.csv"</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>stock_history_2023 <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(esg_proj_2024_data)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stock_history_2023)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute daily returns</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>stock_history_2023[<span class="st">'Return'</span>] <span class="op">=</span> stock_history_2023[<span class="st">'Close'</span>].pct_change()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick peek at data types</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(esg_proj_2024_data.dtypes)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stock_history_2023.dtypes)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows missing key ESG values</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>esg_proj_2024_data <span class="op">=</span> esg_proj_2024_data.dropna(subset<span class="op">=</span>[<span class="st">'Total_ESG'</span>])</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>avg_esg    <span class="op">=</span> esg_proj_2024_data.groupby(<span class="st">'Symbol'</span>)[<span class="st">'Total_ESG'</span>].mean().reset_index()</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>avg_return <span class="op">=</span> stock_history_2023.groupby(<span class="st">'Symbol'</span>)[<span class="st">'Return'</span>].mean().reset_index()</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>company_df <span class="op">=</span> pd.merge(avg_esg, avg_return, on<span class="op">=</span><span class="st">'Symbol'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Year Symbol                                       Name  \
0    2024      A     Agilent Technologies Inc. Common Stock   
1    2024     AA            Alcoa Corporation Common Stock    
2    2024    AAL  American Airlines Group Inc. Common Stock   
3    2024    AAP                    Advance Auto Parts Inc.   
4    2024   AAPL                    Apple Inc. Common Stock   
..    ...    ...                                        ...   
620  2024    XYL                Xylem Inc. Common Stock New   
621  2024    YUM                           Yum! Brands Inc.   
622  2024      Z    Zillow Group Inc. Class C Capital Stock   
623  2024    ZBH   Zimmer Biomet Holdings Inc. Common Stock   
624  2024    ZTS           Zoetis Inc. Class A Common Stock   

                     Sector                                          Industry  \
0               Industrials  Biotechnology: Laboratory Analytical Instruments   
1               Industrials                                          Aluminum   
2    Consumer Discretionary                     Air Freight/Delivery Services   
3    Consumer Discretionary                         Auto &amp; Home Supply Stores   
4                Technology                            Computer Manufacturing   
..                      ...                                               ...   
620             Industrials                                    Fluid Controls   
621  Consumer Discretionary                                       Restaurants   
622  Consumer Discretionary                                 Business Services   
623             Health Care                            Industrial Specialties   
624             Health Care        Biotechnology: Pharmaceutical Preparations   

           Country     Market_Cap  IPO_Year  Total_ESG  Environmental  Social  \
0    United States    40365434818    1999.0       13.6            1.1     6.4   
1    United States     6622135551    2016.0       24.0           13.8     5.9   
2    United States     9088024606       NaN       26.4            9.9    11.6   
3    United States     4474665296       NaN       11.5            0.1     8.3   
4    United States  2614310000000    1980.0       17.2            0.5     7.4   
..             ...            ...       ...        ...            ...     ...   
620  United States    32010402681    2011.0       18.1            4.3     8.7   
621  United States    39885044416       NaN       20.1            4.5    11.4   
622  United States    10195469129       NaN       22.2            1.2    11.5   
623  United States    24476778026       NaN       26.0            3.6    14.5   
624  United States    72535308358    2013.0       18.8            3.2     6.8   

     Governance  Controversy  
0           6.1          2.0  
1           4.3          3.0  
2           4.8          2.0  
3           3.1          2.0  
4           9.4          3.0  
..          ...          ...  
620         5.2          1.0  
621         4.1          2.0  
622         9.5          2.0  
623         7.9          2.0  
624         8.7          2.0  

[625 rows x 13 columns]
              Date  Year Symbol        Open        High         Low  \
0       2023-12-29  2023      A  138.587233  139.215036  137.879691   
1       2023-12-28  2023      A  139.815657  140.084270  138.930245   
2       2023-12-27  2023      A  139.059578  139.437624  138.363189   
3       2023-12-26  2023      A  138.591994  139.746018  138.373126   
4       2023-12-22  2023      A  138.890449  139.636584  138.074668   
...            ...   ...    ...         ...         ...         ...   
157745  2023-01-09  2023    ZTS  146.205080  146.715330  144.242596   
157746  2023-01-06  2023    ZTS  143.840283  145.832203  138.865393   
157747  2023-01-05  2023    ZTS  144.586064  145.400482  141.563836   
157748  2023-01-04  2023    ZTS  146.224720  147.981137  145.184606   
157749  2023-01-03  2023    ZTS  145.871459  145.999010  142.486177   

             Close   Volume  Dividend  Stock_Splits  
0       138.547363  1014400     0.236           0.0  
1       139.049637   892600     0.000           0.0  
2       139.099380  1182300     0.000           0.0  
3       139.089416   948400     0.000           0.0  
4       138.850662  1204100     0.000           0.0  
...            ...      ...       ...           ...  
157745  144.301468  1700500     0.000           0.0  
157746  144.870590  1761200     0.000           0.0  
157747  142.721695  1560900     0.000           0.0  
157748  146.165848  1796100     0.000           0.0  
157749  144.095413  1840600     0.000           0.0  

[157750 rows x 10 columns]
Year               int64
Symbol            object
Name              object
Sector            object
Industry          object
Country           object
Market_Cap         int64
IPO_Year         float64
Total_ESG        float64
Environmental    float64
Social           float64
Governance       float64
Controversy      float64
dtype: object
Date             object
Year              int64
Symbol           object
Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividend        float64
Stock_Splits    float64
Return          float64
dtype: object</code></pre>
</div>
</div>
</section>
<section id="descriptive-statistics" class="level1">
<h1>Descriptive Statistics</h1>
<div id="cell-6" class="cell" data-outputid="306ce488-163a-4e8f-ebfa-010724e48e59" data-execution_count="45">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ESG measures</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>esg_overall <span class="op">=</span> esg_proj_2024_data[[<span class="st">'Total_ESG'</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Environmental'</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Social'</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Governance'</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                      <span class="st">'Controversy'</span>]].describe()</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Stock measures</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>stock_overall <span class="op">=</span> stock_history_2023[[<span class="st">'Close'</span>, <span class="st">'Volume'</span>, <span class="st">'Return'</span>]].describe()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ESG Overall Summary"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(esg_overall)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st"> Stock Overall Summary"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stock_overall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ESG Overall Summary
        Total_ESG  Environmental      Social  Governance  Controversy
count  625.000000     602.000000  602.000000  602.000000   573.000000
mean    21.567040       5.747342    9.017774    6.819103     1.942408
std      7.041637       5.200518    3.567490    2.371114     0.801113
min      6.400000       0.000000    0.800000    2.400000     0.000000
25%     16.300000       1.800000    6.700000    5.225000     1.000000
50%     21.100000       3.950000    8.900000    6.300000     2.000000
75%     26.000000       8.875000   11.175000    7.900000     2.000000
max     52.000000      25.300000   22.500000   19.400000     5.000000

 Stock Overall Summary
               Close        Volume         Return
count  157750.000000  1.577500e+05  157750.000000
mean      138.463043  4.831341e+06       0.000434
std       303.837231  2.183286e+07       0.016063
min         0.980000  0.000000e+00      -0.289855
25%        39.342437  8.251000e+05      -0.008049
50%        79.422333  1.694200e+06       0.000510
75%       146.545551  3.867075e+06       0.008866
max      7024.819824  1.543911e+09       0.427788</code></pre>
</div>
</div>
<p>The summary statistics provide an overview of the distribution and variability in both ESG risk scores and stock market performance for the companies in the dataset.</p>
<p>For the ESG metrics, the average Total ESG risk score is approximately 21.567, with a standard deviation of 7.041, suggesting moderate variability in how companies manage ESG-related risks. Breaking this down further:</p>
<p>Environmental risk has a mean of 5.747,</p>
<p>Social risk averages 9.017, and</p>
<p>Governance risk sits at 6.819</p>
<p>Each with relatively similar spreads standard deviations around 2.5 to 5.2. This balance indicates that no single ESG dimension dominates risk exposure across the dataset, though enviormental has the largest variability.</p>
<p>The Controversy score has a mean of 1.942, but with a maximum value of 5, indicating that while most companies face few controversies, a few outliers experience significant ESG-related issues.</p>
<p>For the stock performance metrics, the average daily closing price is about $138.46, though there is a wide range that reflects the diversity in company sizes and share values with the maximun being $7024.</p>
<p>The average daily return is close to zero 0.000434, as expected in efficient markets, but with a standard deviation of around 0.016, revealing typical short-term fluctuations in stock prices.</p>
<p>Volume varies widely as well, with an average daily trading volume of over 4.83 million shares, but a maximum exceeding 500 million reflecting different company scales and investor interest.</p>
<p>Overall, this descriptive summary illustrates that the companies in the dataset differ significantly in both their ESG profiles and financial behavior. These differences lay the foundation for examining whether and how ESG risk metrics correlate with market performance.</p>
</section>
<section id="statistics-continued" class="level1">
<h1>Statistics Continued</h1>
<div id="cell-9" class="cell" data-outputid="89058d67-e2ea-43e3-bd6d-6071ef3ec554" data-execution_count="46">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>esg_quart <span class="op">=</span> (</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    esg_proj_2024_data</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    .groupby(<span class="st">'Symbol'</span>)[<span class="st">'Total_ESG'</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    .mean()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">'Avg_ESG_Risk'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>esg_quart[<span class="st">'ESG_Quartile'</span>] <span class="op">=</span> pd.qcut(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    esg_quart[<span class="st">'Avg_ESG_Risk'</span>],</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    q<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>[<span class="st">'Low'</span>,<span class="st">'MidLow'</span>,<span class="st">'MidHigh'</span>,<span class="st">'High'</span>]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge quartiles onto daily returns</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>stock_history_2023[<span class="st">'Return'</span>] <span class="op">=</span> stock_history_2023.groupby(<span class="st">'Symbol'</span>)[<span class="st">'Close'</span>].pct_change()</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>merged <span class="op">=</span> pd.merge(</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    stock_history_2023[[<span class="st">'Symbol'</span>,<span class="st">'Return'</span>]],</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    esg_quart[[<span class="st">'Symbol'</span>,<span class="st">'ESG_Quartile'</span>]],</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    on<span class="op">=</span><span class="st">'Symbol'</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">'inner'</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>).dropna(subset<span class="op">=</span>[<span class="st">'Return'</span>])</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by Quartile and financial metrics</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>quartile_stats <span class="op">=</span> merged.groupby(<span class="st">'ESG_Quartile'</span>)[<span class="st">'Return'</span>].agg(</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    Avg_Return <span class="op">=</span> <span class="st">'mean'</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    Volatility <span class="op">=</span> <span class="st">'std'</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    Obs <span class="op">=</span> <span class="st">'count'</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>).reset_index()</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(quartile_stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ESG_Quartile  Avg_Return  Volatility    Obs
0          Low   -0.000243    0.020704  39591
1       MidLow   -0.000585    0.018258  38346
2      MidHigh   -0.000210    0.019483  39093
3         High   -0.000169    0.019358  38595</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  quartile_stats = merged.groupby('ESG_Quartile')['Return'].agg(</code></pre>
</div>
</div>
<p>This code is relevant to the analysis because it investigates the relationship between a company’s ESG risk and its financial performance. Specifically, daily stock returns. It begins by calculating the average ESG risk score for each company. These companies are then divided into four quartiles—Low, MidLow, MidHigh, and High—based on their average ESG risk levels. This classification enables a structured comparison of companies with different levels of ESG exposure.</p>
<p>Next, the code calculates each companys daily return using 2023 stock price data and merges this financial information with the ESG quartile labels. Each quartile averages relatively same returns from -0.000169 to -0.000585 with similar variations in the volatility ranging from 0.018258 to 0.020704.</p>
<p>This allows for a meaningful comparison of whether companies with higher or lower ESG risk tend to perform differently in the stock market, both in terms of return and volatility. As we can see from these statistics, there is not a huge difference in variability, but we will explore this trend further visually.</p>
</section>
<section id="data-visualization" class="level1">
<h1>Data Visualization</h1>
<div id="cell-12" class="cell" data-outputid="37cdaece-afa0-497c-8e6d-d0d97a934771" data-execution_count="27">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average Daily Return Distribution</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">7</span>,<span class="dv">5</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(stock_history_2023[<span class="st">'Return'</span>], kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="op">-</span><span class="fl">0.05</span>, <span class="fl">0.05</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Avg Daily Return Distribution'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Avg Daily Return'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Companies'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_210_Miller_Jacob_stock_ESG (5)_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This histogram illustrates the distribution of average daily stock returns for companies in the 2023 dataset. By limiting the x-axis to a range between -5% and +5%, the plot focuses on typical daily return behavior and filters out extreme outliers. The majority of returns cluster around 0%, indicating that most companies experience relatively small price fluctuations on a day-to-day basis. This visualization is important because it establishes a baseline understanding of how stock returns behave across the entire sample.</p>
<p>Before analyzing differences in financial performance across ESG risk quartiles, it is useful to observe the overall return patterns and identify the range and shape of typical movements. This context helps interpret whether any specific ESG group behaves differently from the general trend.</p>
<p>This appears to be a normal distribution whith no particular sckew in either direction which would be expectex as most companies are concentrated around a very small daily return close to zero.</p>
<div id="cell-14" class="cell" data-outputid="951e8cfb-cc48-41c8-a8c6-beeada4da7ac" data-execution_count="26">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ESG Risk Distribution</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>sns.histplot(esg_proj_2024_data[<span class="st">'Total_ESG'</span>], kde<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'ESG Risk Distribution'</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'ESG Risk Score'</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Frequency'</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_210_Miller_Jacob_stock_ESG (5)_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This histogram shows the distribution of Total ESG Risk Scores for companies in the 2024 dataset. The ESG score reflects a company’s exposure to environmental, social, and governance-related risks, with lower scores indicating lower risk. The shape of the distribution having a right sckew reveals how these risk scores are spread across companies. Most companies tend to fall within a moderate range of ESG risk, with fewer companies showing very low or very high scores.</p>
<p>This visualization is important because it provides an overview of how ESG risks are distributed across the market, which is essential for categorizing companies into meaningful risk groups and for comparing financial performance across varying levels of ESG exposure. It helps set the foundation for examining how ESG risk might relate to stock return behavior. Most companies fall on the lower end of tge ESG Risk Score specturm with a few outliers on the right part of the sckew.</p>
</section>
<section id="combining-return-and-esg-risk" class="level1">
<h1>Combining Return and ESG Risk</h1>
<div id="cell-17" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>stock_history_2023[<span class="st">'Return'</span>] <span class="op">=</span> (stock_history_2023[<span class="st">'Close'</span>] <span class="op">-</span> stock_history_2023[<span class="st">'Open'</span>]) <span class="op">/</span> stock_history_2023[<span class="st">'Open'</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>avg_returns <span class="op">=</span> stock_history_2023.groupby(<span class="st">'Symbol'</span>)[<span class="st">'Return'</span>].mean().reset_index()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>avg_returns.rename(columns<span class="op">=</span>{<span class="st">'Return'</span>: <span class="st">'Avg_Daily_Return'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>company_df <span class="op">=</span> pd.merge(avg_returns, esg_proj_2024_data[[<span class="st">'Symbol'</span>, <span class="st">'Total_ESG'</span>, <span class="st">'Sector'</span>]], on<span class="op">=</span><span class="st">'Symbol'</span>, how<span class="op">=</span><span class="st">'inner'</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-18" class="cell" data-outputid="278cd1f8-1f11-49ba-b2d4-6353a4bef407" data-execution_count="33">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Avg Return vs Avg Total ESG Risk</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">5</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">'Total_ESG'</span>, y<span class="op">=</span><span class="st">'Avg_Daily_Return'</span>, data<span class="op">=</span> company_df, alpha<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Avg Return vs Avg ESG Risk'</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Avg Total ESG Risk'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Avg Daily Return'</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_210_Miller_Jacob_stock_ESG (5)_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This scatterplot illustrates the relationship between a companys average Total ESG Risk score and its average daily stock return. Each point on the graph represents a company, with the x-axis showing its average ESG risk score and the y-axis showing its corresponding average daily return. The dashed horizontal line at y = 0 helps distinguish between companies with positive versus negative average returns. The data points are semi-transparent to reduce overplotting and reveal density.</p>
<p>From the plot, there is no clear linear trend between ESG risk and return—companies are fairly spread across the ESG spectrum, with average returns clustering tightly around zero. However, one notable pattern is that companies with lower ESG risk scores around 10 to 25 appear more concentrated in the positive return range, while those with higher ESG risks above 30 are more dispersed, with several showing negative average returns. This could suggest that firms with stronger ESG profiles lower risk scores may tend to have slightly more consistent or favorable returns, although the relationship is weak and not strictly linear.</p>
<p>The chart implies that ESG risk may have some association with return behavior, but other factors likely play a stronger role. Still, this visualization contributes to the broader analysis by raising the possibility that lower ESG risk is not penalized financially and might align with stable or slightly better performance, which is an important consideration for investors aiming to balance financial and sustainability goals.</p>
</section>
<section id="correlation-and-heat-map" class="level1">
<h1>Correlation and Heat Map</h1>
<div id="cell-21" class="cell" data-outputid="fb3df135-6076-4ed8-ef17-b727a8430547" data-execution_count="43">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>sub_esg <span class="op">=</span> esg_proj_2024_data.groupby(<span class="st">'Symbol'</span>)[[<span class="st">'Environmental'</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">'Social'</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">'Governance'</span>]].mean().reset_index()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>df_corr <span class="op">=</span> (</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    pd.merge(company_df[[<span class="st">'Symbol'</span>,<span class="st">'Total_ESG'</span>,<span class="st">'Avg_Daily_Return'</span>]],</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>             sub_esg, on<span class="op">=</span><span class="st">'Symbol'</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    .set_index(<span class="st">'Symbol'</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    [[<span class="st">'Total_ESG'</span>,<span class="st">'Environmental'</span>,<span class="st">'Social'</span>,<span class="st">'Governance'</span>,<span class="st">'Avg_Daily_Return'</span>]]</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">5</span>))</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>sns.heatmap(df_corr.corr(), annot<span class="op">=</span><span class="va">True</span>, fmt<span class="op">=</span><span class="st">'.2f'</span>, linewidths<span class="op">=</span><span class="fl">0.5</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Correlation: ESG Score and Avg_Daily_Return'</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="danl_210_Miller_Jacob_stock_ESG (5)_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This heatmap visualizes the correlation between different components of ESG and each company’s average daily return. The correlation matrix shows how strongly each pair of variables is linearly related, with values ranging from -1 (perfect negative correlation) to +1 (perfect positive correlation).</p>
<p>The use of color gradients helps quickly identify the strength and direction of each relationship: warmer tones indicate stronger positive correlations, while cooler tones suggest negative correlations. The diagonal shows perfect correlations of each variable with itself (value = 1).</p>
<p>Avg_Daily_Return is negatively correlated with Total_ESG (-0.15), meaning that companies with higher ESG risk tend to have slightly lower average daily returns. This supports the earlier scatterplot findings suggesting that lower ESG risk may be associated with modestly better financial performance.</p>
<p>Environmental (-0.14) and Social (-0.09) risk scores also show slight negative correlations with return, whereas Governance (0.04) has almost no correlation. This implies that environmental and social risk factors may play a slightly larger role in return patterns than governance risk.</p>
<p>Among the ESG components themselves, Total_ESG is strongly correlated with Environmental (0.70) and Social (0.67) risks, indicating that these dimensions heavily influence the overall ESG risk score. Governance has a weaker correlation with Total_ESG (0.38), suggesting it contributes less to overall ESG variation across firms.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This project explored the relationship between ESG risk scores and financial performance by analyzing average daily stock returns across varying ESG profiles. The findings indicate a modest negative correlation between higher ESG risk and financial return, suggesting that companies with lower ESG risks may achieve slightly better market performance. While the relationship is not strong, the consistency across multiple analyses scatterplots, quartile comparisons, and correlation heatmaps suggests that ESG considerations are relevant for investors aiming to align sustainable values with financial outcomes. These insights support the growing case for incorporating ESG metrics into investment strategies.</p>


</section>

</main> <!-- /main -->
<script type="text/javascript" src="links.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Powered with GitHub, Quarto, and Jupyter Notebook<br>© Jacob Miller, 2025</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>